/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const CommonUtil: typeof import('@wot-ui/ui')['CommonUtil']
  const PrinterEscBuilder: typeof import('./utils/printerEsc')['PrinterEscBuilder']
  const buildReceipt: typeof import('./utils/printerEsc')['buildReceipt']
  const computed: typeof import('vue')['computed']
  const createRouter: typeof import('@wot-ui/router')['createRouter']
  const dotFromMm: typeof import('./utils/printerEsc')['dotFromMm']
  const escFourText58: typeof import('./utils/printerEsc')['escFourText58']
  const escThreeText58: typeof import('./utils/printerEsc')['escThreeText58']
  const escTwoText58: typeof import('./utils/printerEsc')['escTwoText58']
  const getCurrentPath: typeof import('./utils/index')['getCurrentPath']
  const nextTick: typeof import('vue')['nextTick']
  const onLaunch: typeof import('@dcloudio/uni-app')['onLaunch']
  const onMounted: typeof import('vue')['onMounted']
  const printerCommandTests: typeof import('./utils/printerCommandTests')['printerCommandTests']
  const ref: typeof import('vue')['ref']
  const useDialog: typeof import('@wot-ui/ui')['useDialog']
  const useNotify: typeof import('@wot-ui/ui')['useNotify']
  const usePrinter: typeof import('./composables/usePrinter')['usePrinter']
  const useRoute: typeof import('@wot-ui/router')['useRoute']
  const useRouter: typeof import('@wot-ui/router')['useRouter']
  const useTabbar: typeof import('./composables/useTabbar')['useTabbar']
  const useToast: typeof import('@wot-ui/ui')['useToast']
}
declare module 'vue' {
  interface ComponentCustomProperties {
    readonly CommonUtil: UnwrapRef<typeof import('@wot-ui/ui')['CommonUtil']>
    readonly PrinterEscBuilder: UnwrapRef<typeof import('./utils/printerEsc')['PrinterEscBuilder']>
    readonly buildReceipt: UnwrapRef<typeof import('./utils/printerEsc')['buildReceipt']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createRouter: UnwrapRef<typeof import('@wot-ui/router')['createRouter']>
    readonly dotFromMm: UnwrapRef<typeof import('./utils/printerEsc')['dotFromMm']>
    readonly escFourText58: UnwrapRef<typeof import('./utils/printerEsc')['escFourText58']>
    readonly escThreeText58: UnwrapRef<typeof import('./utils/printerEsc')['escThreeText58']>
    readonly escTwoText58: UnwrapRef<typeof import('./utils/printerEsc')['escTwoText58']>
    readonly getCurrentPath: UnwrapRef<typeof import('./utils/index')['getCurrentPath']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onLaunch: UnwrapRef<typeof import('@dcloudio/uni-app')['onLaunch']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly printerCommandTests: UnwrapRef<typeof import('./utils/printerCommandTests')['printerCommandTests']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly useDialog: UnwrapRef<typeof import('@wot-ui/ui')['useDialog']>
    readonly useNotify: UnwrapRef<typeof import('@wot-ui/ui')['useNotify']>
    readonly usePrinter: UnwrapRef<typeof import('./composables/usePrinter')['usePrinter']>
    readonly useRoute: UnwrapRef<typeof import('@wot-ui/router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('@wot-ui/router')['useRouter']>
    readonly useTabbar: UnwrapRef<typeof import('./composables/useTabbar')['useTabbar']>
    readonly useToast: UnwrapRef<typeof import('@wot-ui/ui')['useToast']>
  }
}
